version: "3.8"
services:
#  db:
  backend:
    build: ./backend
    ports:
      - "8080:8080"
    volumes:
    - ./backend:/app/backend

    #image: 'openjdk:11'
    # нужна для разработки и запаковки

    #Запускает maven и запаковывает